### ISSUE TITLE
There are no highlighter colors. 

### ISSUE THREAD

**Issue by fkbadur** [ethomasv/RemNoteTheme#12]
There are no highlighter colors. 

Whenever I try to highlight a rem, nothing happens. The rem is tagged as highlighted, but no visual change happens.

I've tried importing the direct code for the highlighting section from both here and another theme, neither work. 

When I disable the dark-mode theme, highlighting works as it should

**Comment by AnweshGangula** [comment]
They are working fine for me. Do you have any other CSS code added other than this?

**Comment by ethomasv** [comment]
Can you tell me did you install the theme with Stylus or Custom CSS Power Rem? 
What theme are you using? 
What another theme did you tried to use for that part?

**Comment by fkbadur** [comment]
I used the custom CSS power rem, originally I just had the import links to dark and light mode, with the light mode disabled.
![image](https://user-images.githubusercontent.com/72461420/95328994-e61b3e00-086b-11eb-8f44-69041b3259db.png)

This is all I had for CSS and the highlighting did not work.

This snippet
![image](https://user-images.githubusercontent.com/72461420/95329094-0a771a80-086c-11eb-8e0b-9ef0bda45816.png)
****
Was taken from https://www.redgregory.com/remnote-content/2020/9/29/7-remnote-css-tips-change-font-and-color#change-remnote-highlight-color

I also previously tried just the highlighting snippet from your code
![image](https://user-images.githubusercontent.com/72461420/95329276-5033e300-086c-11eb-8b4b-d65f42376af2.png)

When I disable your night theme CSS, the highlighting block works find ( I tested by changing the red highlight to a cyan color).

(this sounds dumb) but do chrome extensions have potentially any impact on this? I do have a few that deal with adblocking and privacy and those have caused conflicts with (really unrelated) things in the past.

**Comment by ethomasv** [comment]
If you are using Custom CSS Power Rem, you have to add code from Customizations.css file which you can find here > https://ethomasv.github.io/RemNoteTheme/Customizations.css
In that file you will find code blocks to customize highlight colors, fonts and some other details. 
The reason it is separated is because there are a lot of people who are not comfortable with coding so to make it possible for them to customize some settings it is made as a separate code so that they won't be able to change something that can break the code. But it has to be used with the main theme code in order to make the theme to work properly. 
Stylus allows us to create a menu for user so that people can toggle options and change colors from the menu, so you can just install the theme and forget about the code, but in case you are using Custom CSS feature inside RemNote, you have to add both the theme and the customizations code. Make sure to add Customizations code blocks above the theme import block. 
When you try it out, please let me know if it worked!

**Comment by fkbadur** [comment]
Ohhh!

The highlighting works now, but now there is a separate issue
![image](https://user-images.githubusercontent.com/72461420/95334041-334ede00-0873-11eb-8896-dd6f7db95df5.png)

The CSS blocks colors are all messed up, and invisible when my mouse is over them.

It is not an issue when the new block is turned off

Is this because I imported the whole block, which includes light mode formatting? 

If so, what should I remove or disable in some way

Or should I separate the light and dark code into separate, activatable blocks.

Would you recommend stylus?

**Comment by ethomasv** [comment]
You should separate color blocks for light and dark mode and keep only one active. You can find detailed explanation how to do this in the video https://www.youtube.com/watch?v=d4VqpNyDfqc , skip to 1:40
